#!/bin/bash
sudo apt update && sudo apt upgrade -y

# docker 설치
sudo apt install ca-certificates curl gnupg lsb-release

## docker의 gpg 키 추가
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

## docker 공식 저장소 추가
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt update

## docker CE 설치
sudo apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y

## docker 부팅 설정
sudo systemctl start docker
sudo systemctl enable docker

# java 설치
sudo apt install openjdk-17-jdk -y
