version: "3"
services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    environment:
      STORAGE_TYPE: elasticsearch
      ES_HOSTS: ${ELASTIC_SEARCH_INSTANCE_IP}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_GROUP_ID: zipkin
      ZIPKIN_LOG_LEVEL: DEBUG
      JAVA_OPTS: -verbose:gc -Xms1G -Xmx1G
      # - ES_HTTP_LOGGING=BODY
    ports:
      - 9411:9411
